### ISSUE TITLE
Relationships between tables

### ISSUE THREAD

**Issue by sa-esmaili** [testdrivenio/fastapi-crud-async#1]
Can you please add an example of the tables with relationships (eg: Users that own Notes) in the article or at least give me a clue about it?
The way that FastApi's documentation introduces relationships is different than this tutorial and I like your approach, but couldn't implement two tables with a relationship.

**Comment by mjhea0** [comment]
https://docs.sqlalchemy.org/en/13/core/metadata.html#creating-and-dropping-database-tables
