### ISSUE TITLE
Error during testing

### ISSUE THREAD

**Issue by alam-mahtab** [testdrivenio/fastapi-crud-async#4]
Everything is working awesome, but when i am executing the test comand it throws errors,
you set test_app as a parameter in all the functions issue is from test_app only.
This is the error message.
file /usr/src/app/test/test_notes.py, line 8
  def test_create_note(test_app, monkeypatch):
E       fixture 'test_app' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.
Kindly help me in this.

**Comment by mjhea0** [comment]
make sure to add the test_app fixture to https://github.com/testdrivenio/fastapi-crud-async/blob/master/src/tests/conftest.py
